// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function make(row, col) {
  return /* tuple */[
          row,
          col
        ];
}

function add(param, param$1) {
  return /* tuple */[
          param[0] + param$1[0] | 0,
          param[1] + param$1[1] | 0
        ];
}

exports.make = make;
exports.add = add;
/* No side effect */
