// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Cell$ReasonMazes = require("./Cell.bs.js");

console.log("hello world");

console.log(Cell$ReasonMazes.a);

/*  Not a pure module */
